name: Action 1
on: workflow_dispatch
jobs:
  build_tensorflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Tensorflow
        uses: actions/checkout@main
        with:
          repository: tensorflow/tensorflow
      - run: cd tensorflow
      - name: Bazel Action
        uses: ngalaiko/bazel-action@2.0.0
        with:
          args: build --config=elinux_armhf -c opt //tensorflow/lite:libtensorflowlite.so
#      - run: cd GITHUB_WORKSPACE
#      - run: ls -l
#      - run: bazel build --config=elinux_armhf -c opt //tensorflow/lite:libtensorflowlite.so
#      - run: ls -l
