name: Build EdgeTPU
on: workflow_dispatch
jobs:
  build-edgetpu:
    runs-on: ubuntu-latest
    steps:
      - run: echo '::echo::on'

      - name: Checkout
        uses: actions/checkout@main
        with:
          repository: google-coral/libedgetpu

      - name: Get TF Latest Release
        id: tf-latestrelease
        run: |
          echo "::set-output name=releasetag::$(curl -s https://api.github.com/repos/tensorflow/tensorflow/releases/latest | jq '.tag_name' | sed 's/\"//g')"
          echo ${{ steps.tf-latestrelease.outputs.releasetag }}

      - name: Get Commit
        id: tf-latestcommit
        run: |
          echo "::set-output name=commit::$(git ls-remote https://github.com/tensorflow/tensorflow refs/tags/${{ steps.tf-latestrelease.outputs.releasetag }} | awk '{print $1}')"

      - name: Get SHA256
        id: tf-latesthash
        run: |
          echo "::set-output name=sha256::$(curl -L "https://github.com/tensorflow/tensorflow/archive/${{ steps.tf-latestcommit.outputs.commit }}.tar.gz" | sha256sum | awk '{print $1}')"

      - name: Configure Build
        run: |
          sed -i 's/TENSORFLOW_COMMIT = ".*/TENSORFLOW_COMMIT = "${{ steps.tf-latestcommit.outputs.commit }}"/' ./workspace.bzl
          sed -i 's/TENSORFLOW_SHA256 = ".*/TENSORFLOW_SHA256 = "${{ steps.tf-latesthash.outputs.sha256 }}"/' ./workspace.bzl
          cat ./workspace.bzl
          mkdir artifacts

      - name: Build Docker Image
        run: DOCKER_IMAGE="debian:stretch" make docker-image
        
      - name: Build Direct
        run: |
          DOCKER_CPUS="armv7a" DOCKER_TARGETS=libedgetpu-direct make docker-build
          cp ./out/direct/armv7a/libedgetpu.so.1.0 ./artifacts/direct-stripped-libedgetpu.so
          cp ./bazel-out/armv7a-opt/bin/tflite/public/libedgetpu_direct_all.so ./artifacts/direct-libedgetpu.so

      - name: Build Throttled
        run: |
          DOCKER_CPUS="armv7a" DOCKER_TARGETS=libedgetpu-throttled make docker-build
          cp ./out/throttled/armv7a/libedgetpu.so.1.0 ./artifacts/throttled-stripped-libedgetpu.so
          cp ./bazel-out/armv7a-opt/bin/tflite/public/libedgetpu_direct_all.so ./artifacts/throttled-libedgetpu.so
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with:
          name: build
          path: artifacts

#       - run: DOCKER_CPUS="armv7a" DOCKER_IMAGE="debian:stretch" DOCKER_TARGETS=libedgetpu make docker-build
#       - run: ls -l
#       - run: ls -l -R
#       - run: |
#           cd ./out
#           ls -l
