name: Action 2
on: workflow_dispatch
jobs:
  test_run:
    runs-on: ubuntu-latest
    steps:
      - run: echo '::echo::on'
      - name: Checkout
        uses: actions/checkout@main
        with:
          repository: google-coral/libedgetpu
#      - name: Config
      - run: sed -i 's/TENSORFLOW_COMMIT = ".*/TENSORFLOW_COMMIT = {{ SOME TEXT }}/' ./workspace.bzl
      - run: sed -i 's/TENSORFLOW_SHA256 = ".*/TENSORFLOW_SHA256 = {{ SOME TEXT }}/' ./workspace.bzl
      - run: cat ./workspace.bzl
