# This is a basic workflow to help you get started with Actions

name: Build OpenCV

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-opencv:
    name: Build OpenCV with Modules
    runs-on: ubuntu-latest
    steps:
      - name: Get OpenCV Version
        id: opencv-ver
        run: echo "::set-output name=version::$(echo 4.5.2)"  #get actual version, this is for simplicity
      - name: Get CC Version
        id: cc-arm-ver
        run: echo "::set-output name=version::$(echo v3.0.0)"
      - uses: actions/checkout@main
        with:
          repository: opencv/opencv
          ref: ${{ steps.opencv-ver.outputs.version }}
          path: opencv
      - uses: actions/checkout@main
        with:
          repository: opencv/opencv_contrib
          ref: ${{ steps.opencv-ver.outputs.version }}
          path: opencv-contrib
      - run: |
          sudo apt-get install build-essential cmake pkg-config
          #sudo apt-get install gcc-arm-linux-gnueabihf
          #sudo apt-get install gcc-8-arm-linux-gnueabi-base gcc-8-arm-linux-gnueabihf g++-8-arm-linux-gnueabihf
          #sudo apt-get install eigen
          wget -O toolchain.tar.gz https://github.com/wpilibsuite/raspbian-toolchain/releases/download/${{ steps.cc-arm-ver.outputs.version }}/Raspbian10-Linux-Toolchain-8.3.0.tar.gz
          tar xzf toolchain.tar.gz
          export PATH=$GITHUB_WORKSPACE/raspbian10/bin:${PATH}
          cd $GITHUB_WORKSPACE
          ls -l -r
          mkdir build
          cd build
          cmake $GITHUB_WORKSPACE/opencv \
            -DGNU_MACHINE="arm-raspbian10-linux-gnueabi" \
            #-DCMAKE_C_COMPILER_WORKS=1 -DCMAKE_CXX_COMPILER_WORKS=1 \
            -DSOFTFP=NO \
            -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/opencv/platforms/linux/arm-gnueabi.toolchain.cmake \
            #-DGCC_COMPILER_VERSION=8 \
            -DOPENCV_EXTRA_MODULES_PATH=$GITHUB_WORKSPACE/opencv-contrib/modules/aruco \
            -DBUILD_LIST="" \
            -DWITH_FFMPEG=OFF \
            -DBUILD_JPEG=ON \
            -DBUILD_TESTS=OFF \
            -DBUILD_PERF_TESTS=OFF \
            -DBUILD_opencv_apps=OFF \
            -DBUILD_JAVA=OFF \
            -DBUILD_opencv_python3=OFF \
            -DENABLE_CXX11=ON \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_MAKE_PROGRAM=make \
            -DENABLE_NEON=ON \
            -DENABLE_VFPV3=ON \
          make
          make install
          ls -l -r
          sudo apt-get install zip
          cd $GITHUB_WORKSPACE
          zip -r build.zip build/install
      - uses: actions/upload-artifact@main
        with:
          name: build
          path: build.zip
          
