name: Build Deps
on: workflow_dispatch
jobs:
 
  get-latest-release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.latest-tag.outputs.tag }}
      commit: ${{ steps.latest-commit.outputs.commit }}
      sha256: ${{ steps.latest-hash.outputs.sha256 }}
    steps:
      - run: echo '::echo::on'
      - name: Get latest TF release tag
        id: latest-tag
        run: echo "::set-output name=tag::$(curl -s https://api.github.com/repos/tensorflow/tensorflow/releases/latest | jq '.tag_name' | sed 's/\"//g')"
      - name: Get latest TF commit
        id: latest-commit
        run: echo "::set-output name=commit::$(git ls-remote https://github.com/tensorflow/tensorflow refs/tags/${{ steps.latest-tag.outputs.tag }} | awk '{print $1}')"
      - name: Get latest TF hash code
        id: latest-hash
        run: echo "::set-output name=sha256::$(curl -L "https://github.com/tensorflow/tensorflow/archive/${{ steps.latest-commit.outputs.commit }}.tar.gz" | sha256sum | awk '{print $1}')"
      - name: Confirm Info
        run: |
          echo ${{ steps.latest-tag.outputs.tag }}
          echo ${{ steps.latest-commit.outputs.commit }}
          echo ${{ steps.latest-hash.outputs.sha256 }}
          
  build-tflite:
    runs-on: ubuntu-latest
    needs: get-latest-release
    steps:
      - run: echo '::echo::on'
      - name: Checkout Tensorflow
        uses: actions/checkout@main
        with:
          repository: tensorflow/tensorflow
          ref: ${{ needs.get-latest-release.outputs.tag }}
      - name: Get Deps
        run: |
          npm install @bazel/bazelisk
          pip install numpy
      - name: Build
        run: |
          cd tensorflow
          ls -l
          bazel build --config=elinux_armhf -c opt //tensorflow/lite:libtensorflowlite.so
      - name: Copy Artifact
        run: |
          mkdir artifacts
          find ./tensorflow -name '*.h' | cpio -pdm ./artifacts
          cp bazel-bin/tensorflow/lite/libtensorflowlite.so artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: build-tflite
          path: artifacts
          
  build-edgetpu:
    runs-on: ubuntu-latest
    needs: get-latest-release
    steps:
      - run: echo '::echo::on'

      - name: Checkout Libedgetpu
        uses: actions/checkout@main
        with:
          repository: google-coral/libedgetpu

      - name: Configure Build
        run: |
          sed -i 's/TENSORFLOW_COMMIT = ".*/TENSORFLOW_COMMIT = "${{ needs.get-latest-release.outputs.commit }}"/' ./workspace.bzl
          sed -i 's/TENSORFLOW_SHA256 = ".*/TENSORFLOW_SHA256 = "${{ needs.get-latest-release.outputs.sha256 }}"/' ./workspace.bzl
          sed -i 's/$(STRIPPED_SUFFIX)//' ./Makefile
          cat ./workspace.bzl
          cat ./Makefile
          mkdir -p artifacts/{direct,throttled}
      
      - name: Build
        run: |
         DOCKER_CPUS="armv7a" DOCKER_IMAGE="debian:stretch" DOCKER_TARGETS=libedgetpu make docker-build
         cp out/direct/armv7a/libedgetpu.so.1.0 artifacts/direct/libedgetpu.so
         cp out/throttled/armv7a/libedgetpu.so.1.0 artifacts/throttled/libedgetpu.so
         cp tflite/public/edgetpu.h artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with:
          name: build-edgetpu
          path: artifacts
