name: Build WPILibPi libs
on: workflow_dispatch
jobs:
  build?:
    runs-on: ubuntu-latest
    steps:
      - run: echo '::echo::on'
      - name: Checkout WPILibPi
        uses: actions/checkout@main
        with:
          repository: wpilibsuite/WPILibPi
          ref: $(curl -s https://api.github.com/repos/wpilibsuite/WPILibPi/releases/latest | jq '.tag_name' | sed 's/\"//g')
      - run: apt-get install coreutils quilt parted qemu-user-static debootstrap zerofree zip \
          dosfstools bsdtar libcap2-bin grep rsync xz-utils file git curl bc \
          xxd build-essential cmake python3 python3-distutils ant sudo openjdk-11-jdk
      - run: ./stage3/01-sys-tweaks/01-run.sh
      - run: ls -l
      
