name: Build WPILibPi libs
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo '::echo::on'
      - id: tag
        run: echo "::set-output name=tag::$(curl -s https://api.github.com/repos/wpilibsuite/WPILibPi/releases/latest | jq '.tag_name' | sed 's/\"//g')"
      - name: Checkout WPILibPi
        uses: actions/checkout@main
        with:
          repository: wpilibsuite/WPILibPi
          ref: ${{ steps.tag.outputs.tag }}
      - run: docker build --build-arg BASE_IMAGE=debian:buster -t pi-gen "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
      - run: docker run --rm --privilaged pi-gen base -e -o pipefail -c "./stage3/01-sys-tweaks/01-run.sh && ls -l"
      - run: ls -l
      
