name: Build WPILibPi libs
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo '::echo::on'
      - id: tag
        run: echo "::set-output name=tag::$(curl -s https://api.github.com/repos/wpilibsuite/WPILibPi/releases/latest | jq '.tag_name' | sed 's/\"//g')"
      - name: Checkout WPILibPi
        uses: actions/checkout@main
        with:
          repository: wpilibsuite/WPILibPi
          ref: ${{ steps.tag.outputs.tag }}
      - run: ./docker-build.sh
      - run: ls -l
      - run: ls -l -R
      
