name: Test ModBuild Docker
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - run: echo '::echo::on'
      - uses: actions/checkout@main
      - run: |
          cd /lib/x86_64-linux-gnu; ls -l
          cd $GITHUB_WORKSPACE
          sudo chmod +x {./container.sh,./run.sh}
          sudo ./container.sh
      - if: always()
        run: ls -l -R