name: Test ModBuild Docker
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - run: echo '::echo::on'
      - uses: actions/checkout@main
      - run: |
          sudo ./run.sh
      - if: always()
        run: ls -l -R