name: Test ModBuild Docker
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - run: echo '::echo::on'
      - uses: actions/checkout@main
      - run: cd /; ls -l
      - run: cd /lib; ls -l
      - run: cd /lib32; ls -l
      - run: cd /lib64; ls -l
      - run: cd /libx32; ls -l
      - run: |
          wget -nc -nv https://github.com/wpilibsuite/opensdk/releases/download/v2023-4/armhf-raspi-bullseye-2023-i686-linux-gnu-Toolchain-10.2.0.tgz
          tar xzf ./armhf-raspi-bullseye-2023-i686-linux-gnu-Toolchain-10.2.0.tgz
          export PATH=$GITHUB_WORKSPACE/raspi-bullseye/bin:${PATH}
          ldd $GITHUB_WORKSPACE/raspi-bullseye/bin/armv6-bullseye-linux-gnueabihf-g++
          armv6-bullseye-linux-gnueabihf-g++ --version
      - run: |
          sudo chmod +x {./container.sh,./run.sh}
          sudo ./container.sh
      # - if: always()
      #   run: ls -l -R