on: workflow_dispatch
jobs:
  invoke:
    runs-on: ubuntu-22.04
    steps:
      - run: echo '::echo::on'
      - uses: actions/checkout@main
      - run: |
           docker build - < Dockerfile
          docker run --privilaged bash -e -o pipefail -c "./run.sh"