on: workflow_dispatch
jobs:
  invoke:
    runs-on: ubuntu-latest
    steps:
      - run: echo '::echo::on'
      - run: |
        wget -nc -nv https://github.com/wpilibsuite/opensdk/releases/download/v2023-4/armhf-raspi-bullseye-2023-i686-linux-gnu-Toolchain-10.2.0.tgz
        tar xzf armhf-raspi-bullseye-2023-i686-linux-gnu-Toolchain-10.2.0.tgz
        ./raspi-bullseye/bin/armv6-bullseye-linux-gnueabihf-g++ --version