on: workflow_dispatch
jobs:
  invoke:
    runs-on: ubuntu-22.04
    steps:
      - run: echo '::echo::on'
      - uses: actions/checkout@main
      - run: |
          docker build - < Dockerfile
          ls -l
          docker run bash -e -o pipefail -c "/root/run.sh"