name: PCL Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo '::echo::on'
      - name: Latest PCL Release
        id: pcl-release
        run: echo "release=$(curl -s https://api.github.com/repos/PointCloudLibrary/pcl/releases/latest | jq '.tag_name' | sed 's/\"//g')" >> $GITHUB_OUTPUT

      - name: Checkout PCL
        uses: actions/checkout@main
        with:
          repository: PointCloudLibrary/pcl
          ref: ${{ steps.pcl-release.outputs.release }}

      - name: Build
        run: |
          ls -l
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j2
      
      - name: View
        run: |
          cd build
          ls -l -R
      
      - name: Package
        run: |
          sudo apt-get install zip
          cd ../
          zip -r build.zip build
      
      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: build
          path: build.zip
