name: PCL Build
on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - run: echo '::echo::on'
      

  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo '::echo::on'
      - name: Latest PCL Release
        id: pcl-release
        run: echo "release=$(curl -s https://api.github.com/repos/PointCloudLibrary/pcl/releases/latest | jq '.tag_name' | sed 's/\"//g')" >> $GITHUB_OUTPUT

      - name: Get Deps
        run: |
          sudo apt update
          sudo apt-get install libboost-all-dev libeigen3-dev libflann-dev

      - name: Checkout PCL
        uses: actions/checkout@main
        with:
          repository: PointCloudLibrary/pcl
          ref: ${{ steps.pcl-release.outputs.release }}

      - name: Build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DWITH_VTK=OFF -DWITH_QT=OFF -DWITH_CUDA=OFF -DWITH_PCAP=OFF -DWITH_OPENGL=OFF -DBUILD_visualization=OFF ..
          make -j2
      
      - name: View
        run: |
          ls -l
          cd build
          ls -l -R
      
      - name: Package
        run: |
          sudo apt-get install zip
          ls -l
          zip -r build.zip build
      
      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: build
          path: build.zip
