on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo 'tar xzf "DOWNLOAD_DIR/4.5.2.tar.gz"' | sed -e 's!tar xzf "DOWNLOAD_DIR/4.5.2.tar.gz"!&\ntar xzf "DOWNLOAD_DIR/opencv-contrib.tar.gz"!'
