on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo 'tar xzf "DOWNLOAD_DIR/4.5.2.tar.gz"' | sed -e 's!tar xzf "DOWNLOAD_DIR/4.5.2.tar.gz"!&\ntar xzf "DOWNLOAD_DIR/opencv-contrib.tar.gz"!'
        echo '    https://github.com/opencv/opencv/archive/4.5.2.tar.gz' | sed -e 's!^.*https://github.com/opencv/opencv/archive/4.5.2.tar.gz!&\nwget -nc -nv -O opencv-contrib.tar.gz https://github.com/opencv/opencv_contrib/archive/4.5.2.tar.gz!'
