name: Update Release Artifacts
on:
  push:
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Self
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Create Artifact
        run: |
         touch data.txt
         echo "hello world" >> data.txt
      - name: Update Latest
        uses: ncipollo/release-action@main
        with:
          artifacts: data.txt
          allowUpdates: true
          body: |
            Last Updated: $(date +'%Y-%m-%d')
          commit: $(git rev-parse HEAD)
          prerelease: false
          tag: Latest

