name: Test Maven Download
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo '::echo::on'
      - id: download-maven-artifact
        uses: clausnz/github-action-download-maven-artifact@master
        with:
          url: 'https://frcmaven.wpi.edu/artifactory/'
          repository: 'release'
          groupId: 'edu.wpi.first.apriltag'
          artifactId: 'apriltag-cpp'
          version: '2024.1.1'
          classifier: 'linuxarm64'
          extension: 'zip'
